### ISSUE TITLE
** Error in `python3`: free(): invalid pointer

### ISSUE THREAD

**Issue by xiaoxTM** [yongheng1991/3D-point-capsule-networks#2]
Thank you for releasing such a wonderful project.
I am so interested in your work, and I want to run the source in Docker
where **Error** occurred with the following command:
``` bash
python3 eva_seg.py --model ../../checkpoints/shapenet_part_dataset_ae_200.pth --part_model ../../checkpoints/part_seg_1pecent.p
th --class_choice Airplane
```
**ENVIRONMENT**: pytorch 1.0, cuda10.0 cudnn7 _OR_ pytorch 1.1.0 cuda10.0 cudnn7.5
I tracked this error with pdb, and found it occurred when importing open3d. Strangely, it sometimes occurred when importing **pytorch-related  modules**.

Any idea is welcomed!
Thank you in advance

**Comment by xiaoxTM** [comment]
![open3d-error](https://user-images.githubusercontent.com/11028486/61340883-d4b8d100-a876-11e9-8c2e-6142c20cf551.png)

It seems this error is caused by importing open3d, however, when import open3d from python interactive intererace, no error happened.

**Comment by tolgabirdal** [comment]
Dear @xiaoxTM,

We have never tested this with a Docker container. Currently this is not in our plans. If you find a resolution, please let us know though!

Having said that, your issue seems to be open3d related rather than being a problem of the capsule networks. If this is really the case, you could directly consult the open3d guys. 

We will try to look at the issue, but no promises there : ) 

Thanks for your kind words and mentioning this,

**Comment by xiaoxTM** [comment]
Dear @tolgabirdal :

    Thank you for reply.

    Given that, no error occurred when import *ONLY* open3d from python3,
it is hard to say whether open3d problem or capsule-network problem.

    Amazingly, I found, when I **import open3d before importing other modules**,
it worked, and no more errors occurred.

    Hope this will be helpful for you contributors and other users.

**Comment by tolgabirdal** [comment]
Thanks @xiaoxTM! This is nice to hear. We could update this part.

**Comment by yongheng1991** [comment]
Hi @xiaoxTM,
This problem is caused by the conflict between PyTorch and open3D according to this:
https://github.com/pytorch/pytorch/issues/19739
The first thing you can try is to change the order of importing open3D and torch. (This usually works). You can create the simplest script with just importing these two libraries in different orders to see if this is the problem.  
Hope this could help.

**Comment by denghw** [comment]
Hi @xiaoxTM, it is a conflict between PyTorch and Open3D instead of a problem of capsule-network problem.  I temporarily solved this problem by downgrading Open3D to version 0.5.0.0. 
`pip install open3d-python=0.5.0.0`
In both newest version 0.6.0.0 and  0.7.0.0 of Open3D,  conflicts with PyTorch would be triggered if Open3D is imported after PyTorch. 
Hope this information would be useful.
