### ISSUE TITLE
Guideline for custom dataset

### ISSUE THREAD

**Issue by thhung** [yongheng1991/3D-point-capsule-networks#5]
I would like to train this model on custom dataset for 3d point cloud classification. Could you guide me how to prepare the dataset? Thanks.

**Comment by tolgabirdal** [comment]
Hi @thhung, 

Typically, one needs to implement the data loader if using a custom dataset format is required. However, we have the data loaders for ModelNet40 dataset and for different ShapeNet subsets. How about storing the data in one of those conventions/formats so that you could benefit from the existing loaders? The ShapeNet and ModelNet data structures are now quite standard in 3D vision/graphics and classification is a common task.
