### ISSUE TITLE
Problem in installing Chamfer distance package

### ISSUE THREAD

**Issue by denabazazian** [yongheng1991/3D-point-capsule-networks#6]
I have the following error after running `python build.py install` from `models/nndistance`:

> `nvcc fatal   : Unsupported gpu architecture 'compute_75'`

> `error: command '/usr/bin/nvcc' failed with exit status 1`

I have also tried to add the lines below in `build.py`, but it didn't work: 
`extra_compile_args={`
       `  'cxx': ['-O2',],`
       ` 'nvcc':['--gpu-architecture=compute_70','--gpu-code=sm_70','-O3','-I./cutlass/','-U__CUDA_NO_HALF_OPERATORS__', '-U__CUDA_NO_HALF_CONVERSIONS__']`
           ` }`

++++++++++++++++++++++++
Environment:
`System: ubuntu 18.04`
`Python: 3.6.9`
`PyTorch: 1.3.1`
`CUDA Version: 10.2`
`GPU: GeForce RTX2080Ti`

**Comment by yongheng1991** [comment]
Hi, 
The chamfer distance package has problem with the new version of pytorch since they have modified the way to build c++ extentions. 
I have a new version of chamfer distance package which works with the new pytorch versions(>1.1.0). I will udate them ASAP after passing test procedure. I can also send to you now in case you need it. You need to modify the way of importing the package in the training script. There is an usage example in the "test.py" of this new package that you can refer.
Best,
[torch-nndistance.zip](https://github.com/yongheng1991/3D-point-capsule-networks/files/4049164/torch-nndistance.zip)

**Comment by denabazazian** [comment]
Thanks @yongheng1991 for your reply, it works now!

 I just made a small change in these lines: 

> `cudaconfig = {'home':home, 'nvcc':nvcc,` 
> `'include': pjoin(home, 'include'),`
> `'lib64': pjoin(home, 'lib64')}`

and replaced the `lib64` to `lib` at the last part as below:

> `'lib64': pjoin(home, 'lib')}`

Also, I built PATH and LD_LIBRARY in ~/.bashrc for cuda-10.2 as:
> `export PATH=/usr/local/cuda-10.2/bin${PATH:+:${PATH}}`
> `export LD_LIBRARY_PATH=/usr/local/cuda-10.2/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}`

**Comment by zing235** [comment]
Good to know it works. Good luck.

**Comment by yongheng1991** [comment]
Good to know it works. Good luck.
